#!/usr/bin/env bash

if [[ $1 = --help || $2 == --help || $1 == "" ]]; then
  exec "${0##*/}" help -- "$1"
elif command -v "${0##*/}-$1" &>/dev/null; then
  exec "${0##*/}-$1" "${@:2}"
else
  echo "Unknown command '${0##*/} $1'"
  echo ""
  exec "${0##*/}" help -- "$1"
fi
